name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libtool pkg-config build-essential autoconf automake \
            python3-dev libffi-dev libssl-dev liblzma-dev \
            libsqlite3-dev libncurses5-dev zlib1g-dev libbz2-dev \
            libjpeg-dev libtiff5-dev libsndfile1

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip cython
          pip install buildozer "python-for-android==2024.01.21"
          # ใช้ pyjnius 1.6.1 (รองรับกับ Python 3.11)
          pip install pyjnius==1.6.1

      - name: Accept Android SDK licenses
        working-directory: ./frontend
        run: yes | buildozer android update

      - name: Build with Buildozer
        working-directory: ./frontend
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: medireminder-apk
          path: frontend/bin/*.apk
