name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libtool pkg-config build-essential autoconf automake \
              python3-dev libffi-dev libssl-dev

      # --- *** จุดแก้ไขสำคัญ: เปลี่ยนเป็น Python 3.11 *** ---
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer "python-for-android"

      - name: Build with Buildozer
        working-directory: ./frontend
        run: buildozer -v android debug
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medireminder-apk
          path: frontend/bin/*.apk