# .github/workflows/build-android.yml

name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer "python-for-android==2024.01.21"
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev

      - name: Navigate to frontend directory
        run: cd frontend
      
      # --- *** จุดแก้ไขสำคัญ: เพิ่มขั้นตอนยอมรับ License *** ---
      - name: Accept Android SDK licenses
        working-directory: ./frontend
        run: yes | buildozer android update -v
        
      - name: Build with Buildozer
        working-directory: ./frontend
        run: buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medireminder-apk
          path: frontend/bin/*.apk