# .github/workflows/build-android.yml

name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # <-- 1. ตรึงเวอร์ชันของ Ubuntu ที่เสถียร

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      # --- 2. ติดตั้ง Dependencies ของระบบปฏิบัติการที่จำเป็น ---
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libtool \
              pkg-config \
              build-essential \
              autoconf \
              automake \
              python3-dev \
              libffi-dev \
              libssl-dev \
              liblzma-dev \
              libsqlite3-dev \
              libncurses5-dev \
              zlib1g-dev \
              libbz2-dev

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- 3. ติดตั้ง Dependencies ของ Python ---
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer "python-for-android==2024.01.21"

      # --- 4. รัน Buildozer ---
      - name: Build with Buildozer
        working-directory: ./frontend
        run: buildozer -v android debug
      
      # --- 5. อัปโหลด Artifact ---
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medireminder-apk
          path: frontend/bin/*.apk